# scripts/generate_content.py
"""Generate textbook chapters using Spec‑Kit Plus based on the spec/spec.md file.

This script:
1. Parses `spec/spec.md` (YAML-like front matter or structure).
2. Iterates over the defined chapters.
3. Sends prompts to Spec‑Kit Plus to generate content.
4. Writes output to the `output_dir` defined in the spec.
"""
import os
import subprocess
import re
from pathlib import Path

# Paths
BASE_DIR = Path(__file__).resolve().parent.parent.parent
SPEC_PATH = BASE_DIR / "spec" / "spec.md"

def parse_spec(spec_path: Path):
    """Simple parser for the YAML-like spec file."""
    with open(spec_path, "r", encoding="utf-8") as f:
        content = f.read()
    
    spec = {"chapters": []}
    
    # Extract output_dir
    output_match = re.search(r'output_dir:\s*["\'](.*?)["\']', content)
    if output_match:
        spec["output_dir"] = output_match.group(1)
    else:
        spec["output_dir"] = "../textbook-frontend/docs" # default

    # Extract chapters manually since we might not have PyYAML installed in the environment
    chapter_blocks = re.findall(r'-\s+name:\s*["\'](.*?)["\']\s+description:\s*["\'](.*?)["\']', content, re.DOTALL)
    
    for name, desc in chapter_blocks:
        spec["chapters"].append({"name": name.strip(), "description": desc.strip()})
        
    return spec

def run_spec_kit(prompt: str, output_path: Path) -> None:
    """Run Spec‑Kit Plus with a given prompt and store the result."""
    # Simulation mode for simplicity
    print(f"Generating content for: {output_path.name}...")
    dummy_content = f"# {output_path.stem.replace('-', ' ').title()}\n\n"
    dummy_content += f"**Generative Content Simulation**\n\nPrompt used:\n> {prompt}\n\n"
    dummy_content += "Content generated by Spec-Kit Plus would appear here.\n"
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(dummy_content)

def main():
    if not SPEC_PATH.exists():
        print(f"Spec file not found at {SPEC_PATH}")
        return

    spec = parse_spec(SPEC_PATH)
    # Correct path resolution: absolute path from repo root
    # e.g. spec["output_dir"] = "../textbook-frontend/docs"
    # we take "textbook-frontend/docs" and append to BASE_DIR
    clean_path = spec["output_dir"].replace("../", "").replace("./", "").strip("/")
    output_dir = BASE_DIR / clean_path
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Reading spec from {SPEC_PATH}")
    print(f"Output directory: {output_dir}")
    print(f"Found {len(spec['chapters'])} chapters.")

    for i, chapter in enumerate(spec["chapters"], 1):
        safe_name = re.sub(r'[^a-zA-Z0-9]', '-', chapter['name'].lower()).strip('-')
        filename = f"{safe_name}.md" # Use simpler names if possible, but numbering helps ordering
        filename = f"{i:02d}-{safe_name}.md"
        output_file = output_dir / filename
        
        prompt = (
            f"Write a detailed textbook chapter titled '{chapter['name']}'.\n"
            f"Description: {chapter['description']}\n"
            "Format: Markdown with sections, diagrams, and examples."
        )
        
        run_spec_kit(prompt, output_file)
        print(f"Created {output_file}")

if __name__ == "__main__":
    main()
